name: Windows-RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/b34239c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
    - name: Connect Ngrok
      run: |
        .\ngrok\ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Set Custom Password
      run: |
        net user runneradmin BedavaWindows123! /add
        net localgroup administrators runneradmin /add
    - name: Create Tunnel
      run: |
        Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp 3389"
        Start-Sleep -Seconds 21600
        
